[package]
name = "legionbug"
version = "0.1.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = { git = "https://github.com/TomGillen/legion", features = [ "serialize" ] }
type-uuid = "0.1"
erased-serde = "0.3"
uuid = { version = "0.8", features = ["v4"] }
serde = { version = "1.0.114" }
ron = "0.6.0"
